# Generated by Django 5.2.8 on 2025-11-28 01:39

import cloudinary.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Titulo')),
                ('content', models.TextField(max_length=4000, verbose_name='Contenido')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Fecha de creacion')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagen')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Categoria')),
                ('tag', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Etiquetas')),
            ],
        ),
    ]
